services:
  - type: web
    name: rakib-esrgan-api
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install --no-build-isolation --no-deps ./basicsr-patched
    startCommand: python index.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
